
server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: auth-jwt
          uri: https://github.com/daytolp/micrioservicios-transportes-02.git
          search-paths: config-data
  application:
    name: config-service